package install

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/Nomadcxx/sysc/internal/fetch"
	"github.com/Nomadcxx/sysc/internal/i18n"
	"github.com/Nomadcxx/sysc/internal/pin"
	"github.com/Nomadcxx/sysc/internal/seed"
	"github.com/Nomadcxx/sysc/internal/stamp"
)

func loadPin(t *testing.T) pin.Pin {
	t.Helper()
	data, err := os.ReadFile(filepath.Join("..", "pin", "testdata", "ok.json"))
	if err != nil {
		t.Fatal(err)
	}
	p, err := pin.Decode(data)
	if err != nil {
		t.Fatal(err)
	}
	return p
}

func setupHome(t *testing.T) string {
	t.Helper()
	home := t.TempDir()
	dir := filepath.Join(home, ".config", "niri")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "config.kdl"), []byte("input {}\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	return home
}

func weatherAnswers() seed.Answers {
	return seed.Answers{Latitude: 52.52, Longitude: 13.405, Location: "Berlin"}
}

func noopSystemctl(args ...string) error { return nil }

func TestYesNeedsWeather(t *testing.T) {
	_, err := Run(context.Background(), Options{
		Home:      setupHome(t),
		Pin:       loadPin(t),
		Answers:   seed.Answers{},
		Yes:       true,
		Systemctl: noopSystemctl,
	})
	if err == nil {
		t.Fatal("Run accepted --yes without weather")
	}
}

func TestSkipGSlapperWhenOnPATH(t *testing.T) {
	pkgCalls := 0
	res, err := Run(context.Background(), Options{
		Home:       setupHome(t),
		Pin:        loadPin(t),
		Answers:    weatherAnswers(),
		Yes:        true,
		Download:   func(context.Context, string, []fetch.Asset) error { return nil },
		Swap:       func(string, string, []string) error { return nil },
		LookPath:   func(string) (string, error) { return "/usr/bin/gslapper", nil },
		InstallPkg: func(string) error { pkgCalls++; return nil },
		Systemctl:  noopSystemctl,
		Now:        time.Unix(1000, 0),
	})
	if err != nil {
		t.Fatal(err)
	}
	if pkgCalls != 0 {
		t.Fatalf("package hook called %d times; want 0", pkgCalls)
	}
	found := false
	for _, task := range res.Tasks {
		if task.Name == "gslapper" {
			found = true
			if task.Status != Skipped || task.Reason != "already on PATH" {
				t.Fatalf("gslapper task = %+v", task)
			}
		}
	}
	if !found {
		t.Fatal("no gslapper task")
	}
}

func TestDisabledComponentSkipped(t *testing.T) {
	fetched := map[string]bool{}
	res, err := Run(context.Background(), Options{
		Home:    setupHome(t),
		Pin:     loadPin(t),
		Answers: weatherAnswers(),
		Yes:     true,
		Download: func(_ context.Context, _ string, assets []fetch.Asset) error {
			for _, a := range assets {
				fetched[a.Name] = true
			}
			return nil
		},
		Swap:      func(string, string, []string) error { return nil },
		LookPath:  func(string) (string, error) { return "", os.ErrNotExist },
		Systemctl: noopSystemctl,
		Now:       time.Unix(1000, 0),
	})
	if err != nil {
		t.Fatal(err)
	}
	found := false
	for _, task := range res.Tasks {
		if task.Name == "sysc-terminal" {
			found = true
			if task.Status != Skipped || task.Reason != "no release assets yet" {
				t.Fatalf("terminal task = %+v", task)
			}
		}
	}
	if !found {
		t.Fatal("disabled component missing from task list")
	}
	if fetched["sysc-terminal"] {
		t.Fatal("disabled component was fetched")
	}
	if !fetched["sysc-shell"] || !fetched["sysc-clipboard"] || !fetched["sysc-walls-daemon"] {
		t.Fatalf("enabled components not fetched: %v", fetched)
	}
}

func uninstallHome(t *testing.T) string {
	t.Helper()
	home := t.TempDir()
	stateDir := filepath.Join(home, ".local", "state", "sysc")
	if err := stamp.Write(stateDir, stamp.Stamp{
		Release:    "v0.1.0",
		Components: map[string]string{"sysc-shell": "v0.1.0"},
	}, true); err != nil {
		t.Fatal(err)
	}
	writeFile(t, filepath.Join(home, ".config", "sysc-shell", "config.json"), "{}")
	writeFile(t, filepath.Join(home, ".local", "bin", "sysc-shell"), "bin")
	writeFile(t, filepath.Join(home, ".config", "systemd", "user", "sysc-shell.service"), "unit")
	writeFile(t, filepath.Join(home, ".config", "niri", "config.kdl"), "include \"sysc.kdl\"\ninput {}\n")
	writeFile(t, filepath.Join(home, ".config", "niri", "sysc.kdl"), "// Generated by SYSC. Do not edit.\n")
	return home
}

func writeFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

func exists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

func TestUninstallKeepsConfig(t *testing.T) {
	home := uninstallHome(t)
	if _, err := Uninstall(Options{Home: home, Pin: loadPin(t), Systemctl: noopSystemctl}); err != nil {
		t.Fatal(err)
	}
	if !exists(filepath.Join(home, ".config", "sysc-shell", "config.json")) {
		t.Fatal("keep removed the shell config")
	}
	if exists(filepath.Join(home, ".local", "bin", "sysc-shell")) {
		t.Fatal("binary not removed")
	}
	if exists(filepath.Join(home, ".config", "systemd", "user", "sysc-shell.service")) {
		t.Fatal("unit not removed")
	}
	if exists(filepath.Join(home, ".config", "niri", "sysc.kdl")) {
		t.Fatal("sidecar not removed")
	}
	data, err := os.ReadFile(filepath.Join(home, ".config", "niri", "config.kdl"))
	if err != nil {
		t.Fatal(err)
	}
	if string(data) != "input {}\n" {
		t.Fatalf("include not removed:\n%s", data)
	}
	if exists(filepath.Join(home, ".local", "state", "sysc", stamp.FileName)) {
		t.Fatal("stamp not removed")
	}
}

func TestUninstallPurge(t *testing.T) {
	home := uninstallHome(t)
	if _, err := Uninstall(Options{Home: home, Pin: loadPin(t), Purge: true, Systemctl: noopSystemctl}); err != nil {
		t.Fatal(err)
	}
	if exists(filepath.Join(home, ".config", "sysc-shell", "config.json")) {
		t.Fatal("purge left the shell config")
	}
}

// A live niri (WAYLAND_DISPLAY + NIRI_SOCKET) whose graphical-session.target
// is inactive was started as plain `niri`, not niri-session. Commenting the
// user's spawn line there removes the only autostart; the units cannot start.
func TestNiriSessionInactiveGraphicalTargetKeepsSpawn(t *testing.T) {
	home := setupHome(t)
	t.Setenv("XDG_CONFIG_HOME", "")
	t.Setenv("XDG_STATE_HOME", "")
	config := filepath.Join(home, ".config", "niri", "config.kdl")
	const original = "spawn-at-startup \"sysc-shell\"\ninput {}\n"
	if err := os.WriteFile(config, []byte(original), 0o644); err != nil {
		t.Fatal(err)
	}
	var calls []string
	loc := i18n.EN
	res, err := Run(context.Background(), Options{
		Home:          home,
		Pin:           loadPin(t),
		Answers:       weatherAnswers(),
		Yes:           true,
		InNiriSession: true,
		Loc:           &loc,
		Download:      func(context.Context, string, []fetch.Asset) error { return nil },
		Swap:          func(string, string, []string) error { return nil },
		LookPath:      func(string) (string, error) { return "", os.ErrNotExist },
		Systemctl: func(args ...string) error {
			calls = append(calls, strings.Join(args, " "))
			if len(args) > 0 && args[0] == "is-active" {
				return fmt.Errorf("inactive")
			}
			return nil
		},
		Now: time.Unix(1000, 0),
	})
	if err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(config)
	if err != nil {
		t.Fatal(err)
	}
	text := string(data)
	if strings.Contains(text, `// spawn-at-startup "sysc-shell"`) {
		t.Fatalf("autostart commented while graphical-session.target is inactive:\n%s", text)
	}
	if !strings.Contains(text, `spawn-at-startup "sysc-shell"`) {
		t.Fatalf("spawn line missing:\n%s", text)
	}
	if !strings.Contains(text, `include "sysc.kdl"`) {
		t.Fatalf("sidecar include missing:\n%s", text)
	}
	if res.Stamp.Started {
		t.Fatal("stamp claims units started")
	}
	sawInactiveCheck := false
	enabled, started := false, false
	for _, call := range calls {
		switch {
		case strings.HasPrefix(call, "is-active"):
			if strings.Contains(call, "graphical-session.target") {
				sawInactiveCheck = true
			} else if !strings.HasSuffix(call, ".service") {
				t.Fatalf("unexpected is-active probe %q", call)
			}
		case strings.HasPrefix(call, "enable "):
			enabled = true
		case strings.HasPrefix(call, "start "):
			started = true
		}
	}
	if !sawInactiveCheck {
		t.Fatal("systemctl is-active graphical-session.target was not called")
	}
	if !enabled {
		t.Fatal("units were not enabled")
	}
	if started {
		t.Fatal("units were started despite inactive graphical-session.target")
	}
	if !strings.Contains(res.SessionWarning, "niri-session") {
		t.Fatalf("session warning = %q, want a niri-session message", res.SessionWarning)
	}
}

// SSH / no-Wayland installs stay enable-only: the spawn line is still commented
// so a later niri-session does not start the shell twice, and nothing is started.
func TestNoWaylandInstallEnablesWithoutStarting(t *testing.T) {
	home := setupHome(t)
	t.Setenv("XDG_CONFIG_HOME", "")
	t.Setenv("XDG_STATE_HOME", "")
	config := filepath.Join(home, ".config", "niri", "config.kdl")
	if err := os.WriteFile(config, []byte("spawn-at-startup \"sysc-shell\"\ninput {}\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	var calls []string
	res, err := Run(context.Background(), Options{
		Home:     home,
		Pin:      loadPin(t),
		Answers:  weatherAnswers(),
		Yes:      true,
		Download: func(context.Context, string, []fetch.Asset) error { return nil },
		Swap:     func(string, string, []string) error { return nil },
		LookPath: func(string) (string, error) { return "", os.ErrNotExist },
		Systemctl: func(args ...string) error {
			calls = append(calls, strings.Join(args, " "))
			if len(args) > 0 && args[0] == "is-active" {
				return fmt.Errorf("inactive")
			}
			return nil
		},
		Now: time.Unix(1000, 0),
	})
	if err != nil {
		t.Fatalf("SSH install failed: %v", err)
	}
	if res.Stamp.Started {
		t.Fatal("SSH install started units")
	}
	if res.SessionWarning != "" {
		t.Fatalf("SSH install warned about a live niri session: %q", res.SessionWarning)
	}
	data, err := os.ReadFile(config)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(data), `// spawn-at-startup "sysc-shell"`) {
		t.Fatalf("SSH install left the shell spawn live:\n%s", data)
	}
	enabled, started := false, false
	for _, call := range calls {
		if strings.HasPrefix(call, "enable ") {
			enabled = true
		}
		if strings.HasPrefix(call, "start ") {
			started = true
		}
	}
	if !enabled || started {
		t.Fatalf("enable=%v start=%v, want enable only; calls=%v", enabled, started, calls)
	}
}

func TestLiveNiriSessionStartsAndCommentsSpawn(t *testing.T) {
	home := setupHome(t)
	t.Setenv("XDG_CONFIG_HOME", "")
	t.Setenv("XDG_STATE_HOME", "")
	config := filepath.Join(home, ".config", "niri", "config.kdl")
	if err := os.WriteFile(config, []byte("spawn-at-startup \"sysc-shell\"\ninput {}\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	started := false
	res, err := Run(context.Background(), Options{
		Home:          home,
		Pin:           loadPin(t),
		Answers:       weatherAnswers(),
		Yes:           true,
		InNiriSession: true,
		Download:      func(context.Context, string, []fetch.Asset) error { return nil },
		Swap:          func(string, string, []string) error { return nil },
		LookPath:      func(string) (string, error) { return "", os.ErrNotExist },
		Systemctl: func(args ...string) error {
			if len(args) > 0 && args[0] == "start" {
				started = true
			}
			return nil
		},
		Now: time.Unix(1000, 0),
	})
	if err != nil {
		t.Fatal(err)
	}
	if !res.Stamp.Started || !started {
		t.Fatalf("stamp.Started=%v systemctl start=%v", res.Stamp.Started, started)
	}
	if res.SessionWarning != "" {
		t.Fatalf("active niri-session warned: %q", res.SessionWarning)
	}
	data, err := os.ReadFile(config)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(data), `// spawn-at-startup "sysc-shell"`) {
		t.Fatalf("spawn not commented under an active graphical session:\n%s", data)
	}
}

func TestUninstallGSlapperGatedOnStamp(t *testing.T) {
	home := uninstallHome(t)
	removed := 0
	opts := Options{Home: home, Pin: loadPin(t), RemoveGSlapper: true, Systemctl: noopSystemctl,
		RemovePkg: func(string) error { removed++; return nil }}
	if _, err := Uninstall(opts); err != nil {
		t.Fatal(err)
	}
	if removed != 0 {
		t.Fatalf("gslapper removed %d times; stamp says SYSC did not install it", removed)
	}

	home = uninstallHome(t)
	if err := stamp.Write(filepath.Join(home, ".local", "state", "sysc"), stamp.Stamp{
		Release:           "v0.1.0",
		Components:        map[string]string{"sysc-shell": "v0.1.0"},
		GSlapperInstalled: true,
	}, true); err != nil {
		t.Fatal(err)
	}
	opts.Home = home
	if _, err := Uninstall(opts); err != nil {
		t.Fatal(err)
	}
	if removed != 1 {
		t.Fatalf("gslapper removed %d times; want 1", removed)
	}
}

func versionedDownload(version string) func(context.Context, string, []fetch.Asset) error {
	return func(_ context.Context, staging string, assets []fetch.Asset) error {
		if err := os.MkdirAll(staging, 0o755); err != nil {
			return err
		}
		for _, a := range assets {
			if err := os.WriteFile(filepath.Join(staging, a.Name), []byte(version+"-"+a.Name), 0o755); err != nil {
				return err
			}
		}
		return nil
	}
}

func installOpts(t *testing.T, home, version string) Options {
	t.Helper()
	return Options{
		Home:      home,
		Pin:       loadPin(t),
		Answers:   weatherAnswers(),
		Yes:       true,
		Download:  versionedDownload(version),
		LookPath:  func(string) (string, error) { return "", os.ErrNotExist },
		Systemctl: noopSystemctl,
		Now:       time.Unix(1000, 0),
	}
}

func TestUpgradeThenUninstallRemovesBaks(t *testing.T) {
	home := setupHome(t)
	if _, err := Run(context.Background(), installOpts(t, home, "v1")); err != nil {
		t.Fatal(err)
	}
	if _, err := Run(context.Background(), installOpts(t, home, "v2")); err != nil {
		t.Fatal(err)
	}
	binDir := filepath.Join(home, ".local", "bin")
	names := []string{"sysc-shell", "sysc-clipboard", "sysc-walls-daemon"}
	for _, name := range names {
		data, err := os.ReadFile(filepath.Join(binDir, name+".bak"))
		if err != nil {
			t.Fatalf("upgrade did not leave %s.bak: %v", name, err)
		}
		if string(data) != "v1-"+name {
			t.Fatalf("%s.bak = %q, want v1 backup", name, data)
		}
	}
	if _, err := Uninstall(Options{Home: home, Pin: loadPin(t), Systemctl: noopSystemctl}); err != nil {
		t.Fatal(err)
	}
	for _, name := range names {
		if exists(filepath.Join(binDir, name)) {
			t.Errorf("uninstall left %s", name)
		}
		if exists(filepath.Join(binDir, name+".bak")) {
			t.Errorf("uninstall left %s.bak", name)
		}
	}
}

func TestFailedFreshInstallIgnoresStaleBak(t *testing.T) {
	home := setupHome(t)
	binDir := filepath.Join(home, ".local", "bin")
	if err := os.MkdirAll(binDir, 0o755); err != nil {
		t.Fatal(err)
	}
	const stale = "v1-sysc-shell"
	if err := os.WriteFile(filepath.Join(binDir, "sysc-shell.bak"), []byte(stale), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink("/nonexistent", filepath.Join(binDir, "sysc-clipboard")); err != nil {
		t.Fatal(err)
	}
	_, err := Run(context.Background(), installOpts(t, home, "v3"))
	if err == nil {
		t.Fatal("expected swap to refuse the symlinked binary")
	}
	shell := filepath.Join(binDir, "sysc-shell")
	if data, readErr := os.ReadFile(shell); readErr == nil {
		t.Fatalf("failed fresh install left %s = %q; want the new binary removed", shell, data)
	}
}

// TestMain makes Options.Home authoritative for the whole package.
// xdgConfig and xdgState prefer $XDG_CONFIG_HOME/$XDG_STATE_HOME, and a CI
// runner exports both, so without this every test reads the runner's real
// config instead of its own temp home.
func TestMain(m *testing.M) {
	os.Unsetenv("XDG_CONFIG_HOME")
	os.Unsetenv("XDG_STATE_HOME")
	os.Exit(m.Run())
}
