package install

import (
	"context"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/Nomadcxx/sysc/internal/fetch"
	"github.com/Nomadcxx/sysc/internal/pin"
	"github.com/Nomadcxx/sysc/internal/seed"
	"github.com/Nomadcxx/sysc/internal/stamp"
)

func loadPin(t *testing.T) pin.Pin {
	t.Helper()
	data, err := os.ReadFile(filepath.Join("..", "pin", "testdata", "ok.json"))
	if err != nil {
		t.Fatal(err)
	}
	p, err := pin.Decode(data)
	if err != nil {
		t.Fatal(err)
	}
	return p
}

func setupHome(t *testing.T) string {
	t.Helper()
	home := t.TempDir()
	dir := filepath.Join(home, ".config", "niri")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "config.kdl"), []byte("input {}\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	return home
}

func weatherAnswers() seed.Answers {
	return seed.Answers{Latitude: 52.52, Longitude: 13.405, Location: "Berlin"}
}

func noopSystemctl(args ...string) error { return nil }

func TestYesNeedsWeather(t *testing.T) {
	_, err := Run(context.Background(), Options{
		Home:      setupHome(t),
		Pin:       loadPin(t),
		Answers:   seed.Answers{},
		Yes:       true,
		Systemctl: noopSystemctl,
	})
	if err == nil {
		t.Fatal("Run accepted --yes without weather")
	}
}

func TestSkipGSlapperWhenOnPATH(t *testing.T) {
	pkgCalls := 0
	res, err := Run(context.Background(), Options{
		Home:       setupHome(t),
		Pin:        loadPin(t),
		Answers:    weatherAnswers(),
		Yes:        true,
		Download:   func(context.Context, string, []fetch.Asset) error { return nil },
		Swap:       func(string, string, []string) error { return nil },
		LookPath:   func(string) (string, error) { return "/usr/bin/gslapper", nil },
		InstallPkg: func(string) error { pkgCalls++; return nil },
		Systemctl:  noopSystemctl,
		Now:        time.Unix(1000, 0),
	})
	if err != nil {
		t.Fatal(err)
	}
	if pkgCalls != 0 {
		t.Fatalf("package hook called %d times; want 0", pkgCalls)
	}
	found := false
	for _, task := range res.Tasks {
		if task.Name == "gslapper" {
			found = true
			if task.Status != Skipped || task.Reason != "already on PATH" {
				t.Fatalf("gslapper task = %+v", task)
			}
		}
	}
	if !found {
		t.Fatal("no gslapper task")
	}
}

func TestDisabledComponentSkipped(t *testing.T) {
	fetched := map[string]bool{}
	res, err := Run(context.Background(), Options{
		Home:    setupHome(t),
		Pin:     loadPin(t),
		Answers: weatherAnswers(),
		Yes:     true,
		Download: func(_ context.Context, _ string, assets []fetch.Asset) error {
			for _, a := range assets {
				fetched[a.Name] = true
			}
			return nil
		},
		Swap:      func(string, string, []string) error { return nil },
		LookPath:  func(string) (string, error) { return "", os.ErrNotExist },
		Systemctl: noopSystemctl,
		Now:       time.Unix(1000, 0),
	})
	if err != nil {
		t.Fatal(err)
	}
	found := false
	for _, task := range res.Tasks {
		if task.Name == "sysc-terminal" {
			found = true
			if task.Status != Skipped || task.Reason != "no release assets yet" {
				t.Fatalf("terminal task = %+v", task)
			}
		}
	}
	if !found {
		t.Fatal("disabled component missing from task list")
	}
	if fetched["sysc-terminal"] {
		t.Fatal("disabled component was fetched")
	}
	if !fetched["sysc-shell"] || !fetched["sysc-clipboard"] || !fetched["sysc-walls-daemon"] {
		t.Fatalf("enabled components not fetched: %v", fetched)
	}
}

func uninstallHome(t *testing.T) string {
	t.Helper()
	home := t.TempDir()
	stateDir := filepath.Join(home, ".local", "state", "sysc")
	if err := stamp.Write(stateDir, stamp.Stamp{
		Release:    "v0.1.0",
		Components: map[string]string{"sysc-shell": "v0.1.0"},
	}, true); err != nil {
		t.Fatal(err)
	}
	writeFile(t, filepath.Join(home, ".config", "sysc-shell", "config.json"), "{}")
	writeFile(t, filepath.Join(home, ".local", "bin", "sysc-shell"), "bin")
	writeFile(t, filepath.Join(home, ".config", "systemd", "user", "sysc-shell.service"), "unit")
	writeFile(t, filepath.Join(home, ".config", "niri", "config.kdl"), "include \"sysc.kdl\"\ninput {}\n")
	writeFile(t, filepath.Join(home, ".config", "niri", "sysc.kdl"), "// Generated by SYSC. Do not edit.\n")
	return home
}

func writeFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

func exists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

func TestUninstallKeepsConfig(t *testing.T) {
	home := uninstallHome(t)
	if _, err := Uninstall(Options{Home: home, Pin: loadPin(t), Systemctl: noopSystemctl}); err != nil {
		t.Fatal(err)
	}
	if !exists(filepath.Join(home, ".config", "sysc-shell", "config.json")) {
		t.Fatal("keep removed the shell config")
	}
	if exists(filepath.Join(home, ".local", "bin", "sysc-shell")) {
		t.Fatal("binary not removed")
	}
	if exists(filepath.Join(home, ".config", "systemd", "user", "sysc-shell.service")) {
		t.Fatal("unit not removed")
	}
	if exists(filepath.Join(home, ".config", "niri", "sysc.kdl")) {
		t.Fatal("sidecar not removed")
	}
	data, err := os.ReadFile(filepath.Join(home, ".config", "niri", "config.kdl"))
	if err != nil {
		t.Fatal(err)
	}
	if string(data) != "input {}\n" {
		t.Fatalf("include not removed:\n%s", data)
	}
	if exists(filepath.Join(home, ".local", "state", "sysc", stamp.FileName)) {
		t.Fatal("stamp not removed")
	}
}

func TestUninstallPurge(t *testing.T) {
	home := uninstallHome(t)
	if _, err := Uninstall(Options{Home: home, Pin: loadPin(t), Purge: true, Systemctl: noopSystemctl}); err != nil {
		t.Fatal(err)
	}
	if exists(filepath.Join(home, ".config", "sysc-shell", "config.json")) {
		t.Fatal("purge left the shell config")
	}
}

func TestUninstallGSlapperGatedOnStamp(t *testing.T) {
	home := uninstallHome(t)
	removed := 0
	opts := Options{Home: home, Pin: loadPin(t), RemoveGSlapper: true, Systemctl: noopSystemctl,
		RemovePkg: func(string) error { removed++; return nil }}
	if _, err := Uninstall(opts); err != nil {
		t.Fatal(err)
	}
	if removed != 0 {
		t.Fatalf("gslapper removed %d times; stamp says SYSC did not install it", removed)
	}

	home = uninstallHome(t)
	if err := stamp.Write(filepath.Join(home, ".local", "state", "sysc"), stamp.Stamp{
		Release:           "v0.1.0",
		Components:        map[string]string{"sysc-shell": "v0.1.0"},
		GSlapperInstalled: true,
	}, true); err != nil {
		t.Fatal(err)
	}
	opts.Home = home
	if _, err := Uninstall(opts); err != nil {
		t.Fatal(err)
	}
	if removed != 1 {
		t.Fatalf("gslapper removed %d times; want 1", removed)
	}
}
