// Package niri edits the user's Niri config through a SYSC-owned sidecar.
package niri

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"syscall"
	"time"

	"github.com/Nomadcxx/sysc/internal/backup"
)

const marker = "// Generated by SYSC. Do not edit."

// Bind is one recommended key binding for the sidecar.
type Bind struct {
	Key    string
	Action string
}

// DefaultBinds are the recommended sysc-shell ipc bindings.
var DefaultBinds = []Bind{
	{Key: "Mod+Space", Action: `spawn "sysc-shell" "ipc" "panel.toggle" "{\"panel\":\"launcher\"}"`},
	{Key: "Mod+Comma", Action: `spawn "sysc-shell" "ipc" "panel.open" "{\"panel\":\"settings\"}"`},
}

// Options configures Apply.
type Options struct {
	ConfigPath  string
	SidecarPath string
	StateDir    string
	Binds       []Bind
	Now         time.Time
}

// Result reports what Apply changed.
type Result struct {
	IncludeAdded   bool
	SpawnCommented int
	BindsAdded     []string
	BindsSkipped   []string
}

var (
	includeRe  = regexp.MustCompile(`(?m)^\s*include\s+"sysc\.kdl"[ \t]*(?://[^\n]*)?[ \t]*\r?\n?`)
	spawnRe    = regexp.MustCompile(`(?m)^([ \t]*)spawn-at-startup[ \t]+"sysc-shell"`)
	spawnOffRe = regexp.MustCompile(`(?m)^([ \t]*)// (spawn-at-startup[ \t]+"sysc-shell")`)
	incFileRe  = regexp.MustCompile(`(?m)^\s*include\s+"([^"]+)"`)
)

// Apply comments sysc-shell spawn lines, ensures the sidecar include, and
// writes the sidecar with every recommended bind whose key is free.
func Apply(opts Options) (Result, error) {
	var res Result
	data, err := os.ReadFile(opts.ConfigPath)
	if err != nil {
		if os.IsNotExist(err) {
			return res, fmt.Errorf("niri config not found at %s", opts.ConfigPath)
		}
		return res, err
	}
	text := string(data)

	commented := spawnRe.ReplaceAllString(text, "$1// spawn-at-startup \"sysc-shell\"")
	res.SpawnCommented = len(spawnRe.FindAllString(text, -1))
	text = commented

	if !includeRe.MatchString(text) {
		nl := "\n"
		if strings.Contains(text, "\r\n") {
			nl = "\r\n"
		}
		if !strings.HasSuffix(text, "\n") {
			text += nl
		}
		text += "include \"sysc.kdl\"" + nl
		res.IncludeAdded = true
	}

	if text != string(data) {
		if _, err := backup.FirstBak(opts.ConfigPath); err != nil {
			return res, err
		}
		if _, err := backup.StateCopy(opts.StateDir, "niri-config.kdl", opts.ConfigPath, opts.Now); err != nil {
			return res, err
		}
		if err := writeAtomic(opts.ConfigPath, []byte(text)); err != nil {
			return res, err
		}
	}

	occupied := occupiedKeys(opts, text, opts.Binds)
	var body strings.Builder
	body.WriteString(marker + "\n")
	body.WriteString("// SYSC owns this file; changes are overwritten on update.\n\n")
	// Included files are full config fragments. Binds outside binds { } are
	// rejected ("unexpected node") and the include fails the whole config.
	body.WriteString("binds {\n")
	for _, b := range opts.Binds {
		if occupied[b.Key] {
			res.BindsSkipped = append(res.BindsSkipped, b.Key)
			continue
		}
		fmt.Fprintf(&body, "    %s { %s; }\n", b.Key, b.Action)
		res.BindsAdded = append(res.BindsAdded, b.Key)
	}
	body.WriteString("}\n")

	if existing, err := os.ReadFile(opts.SidecarPath); err == nil && !strings.Contains(string(existing), marker) {
		if _, err := backup.FirstBak(opts.SidecarPath); err != nil {
			return res, err
		}
	}
	if err := writeAtomic(opts.SidecarPath, []byte(body.String())); err != nil {
		return res, err
	}
	return res, nil
}

// occupiedKeys reports every bind key already present in the config or its
// live includes. The SYSC-owned sidecar is excluded: its binds are ours to
// rewrite, and counting them as occupied would strip them on reinstall.
func occupiedKeys(opts Options, text string, binds []Bind) map[string]bool {
	all := text
	dir := filepath.Dir(opts.ConfigPath)
	sidecar := filepath.Clean(opts.SidecarPath)
	for _, m := range incFileRe.FindAllStringSubmatch(text, -1) {
		inc := filepath.Join(dir, m[1])
		if filepath.Clean(inc) == sidecar {
			continue
		}
		if data, err := os.ReadFile(inc); err == nil {
			all += "\n" + string(data)
		}
	}
	occupied := map[string]bool{}
	for _, b := range binds {
		re := regexp.MustCompile(`(?m)^\s*` + regexp.QuoteMeta(b.Key) + `\b`)
		if re.MatchString(all) {
			occupied[b.Key] = true
		}
	}
	return occupied
}

// Remove deletes the sidecar and the include line, and re-enables the
// sysc-shell autostart lines Apply commented out.
func Remove(opts Options) error {
	if data, err := os.ReadFile(opts.ConfigPath); err == nil {
		text := includeRe.ReplaceAllString(string(data), "")
		// ponytail: a line the user commented themselves before install is
		// indistinguishable from ours and also returns; track per-line
		// provenance in the stamp if that ever bites.
		text = spawnOffRe.ReplaceAllString(text, "$1$2")
		if text != string(data) {
			if err := writeAtomic(opts.ConfigPath, []byte(text)); err != nil {
				return err
			}
		}
	} else if !os.IsNotExist(err) {
		return err
	}
	if err := os.Remove(opts.SidecarPath); err != nil && !os.IsNotExist(err) {
		return err
	}
	return nil
}

// writeAtomic replaces the contents of path by writing a sibling temp file
// and renaming it into place. A symlink is resolved first: renaming onto the
// link would replace it with a regular file and detach a stow, chezmoi, or
// home-manager config. The link stays, and the edit lands on the file it
// names. A target the user cannot write, such as a Nix store path, is a
// named error.
func writeAtomic(path string, data []byte) error {
	dest, viaLink, err := writeDest(path)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(dest), 0o755); err != nil {
		return destWriteErr(path, dest, viaLink, err)
	}
	tmp := dest + ".tmp"
	if err := os.WriteFile(tmp, data, 0o644); err != nil {
		os.Remove(tmp)
		return destWriteErr(path, dest, viaLink, err)
	}
	if err := os.Rename(tmp, dest); err != nil {
		os.Remove(tmp)
		return destWriteErr(path, dest, viaLink, err)
	}
	return nil
}

// writeDest returns the path to replace. A missing path is returned as-is so
// a new sidecar can be created. A symlink resolves to its final target.
func writeDest(path string) (dest string, viaLink bool, err error) {
	fi, err := os.Lstat(path)
	if err != nil {
		if os.IsNotExist(err) {
			return path, false, nil
		}
		return "", false, err
	}
	if fi.Mode()&os.ModeSymlink == 0 {
		return path, false, nil
	}
	resolved, err := filepath.EvalSymlinks(path)
	if err != nil {
		return "", false, fmt.Errorf("refusing to edit %s: symlink cannot be resolved: %w", path, err)
	}
	return resolved, true, nil
}

func destWriteErr(path, dest string, viaLink bool, err error) error {
	if viaLink && isNotWritable(err) {
		return fmt.Errorf("refusing to edit %s: symlink target %s is not writable: %w", path, dest, err)
	}
	return err
}

func isNotWritable(err error) bool {
	return errors.Is(err, syscall.EACCES) || errors.Is(err, syscall.EPERM) || errors.Is(err, syscall.EROFS)
}
